{{- if .Values.sso.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ .Values.sso.secretName }}
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    {{- range $key, $val := .Values.sealedSecret.encryptedData }}
    {{ $key }}: {{ $val }}
    {{- end }}
  template:
    metadata:
      creationTimestamp: null
{{- end }}
